### ISSUE TITLE
Feature Request: Custom Build Tasks

### ISSUE THREAD

**Issue by uluzox** [SAP/ui5-cli#191]
## Expected Behavior
It should be possible to add a custom task that can be added to the build job via `--include-task`.
```
ui5 build --all --include-task=myCustomTask 
```
The custom task shall be located in my project's sources.
 
## Current Behavior
No custom task can be defined without forking this project.

**Comment by codeworrior** [comment]
Did you notice https://github.com/SAP/ui5-project/blob/master/docs/BuildExtensibility.md ?

**Comment by uluzox** [comment]
Hi @codeworrior,

I did not see this before and it looks promissing. With command line arguments, I would be able to customise my build when executing it. I understand that I can include and exclude task using the command line. However, with ui5-cli's build definition being based on the `ui5.yaml`, I would prefer a possibility to actively specify the yaml file used for a build.

This way the build process could vary depending on the targeted infrastructure:
* `ui5 build --file=ui5.prod.yaml`
* `ui5 build --file=ui5.test.yaml`
* `ui5 build --file=ui5.dev.yaml`
* ...

I did not find this option. Does it exist?

Kind regards,
Thorsten

**Comment by svbender** [comment]
Yes this works with `ui5 build --config=ui5.prod.yaml`

**Comment by uluzox** [comment]
Thank you :-)

**Comment by RandomByte** [comment]
For future reference, the full UI5 CLI reference can be found here: https://github.com/SAP/ui5-cli#cli-usage
