### ISSUE TITLE
ui5.yaml Docs

### ISSUE THREAD

**Issue by cschuff** [SAP/ui5-cli#21]
Where can I find docs about all the config options of ui5.yaml?

## Affected components
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by RandomByte** [comment]
Some things are still missing, but mostly here: [SAP/ui5-project#configuration](https://github.com/SAP/ui5-project#configuration)

We should add a reference to that in this repos readme 👍

**Comment by cschuff** [comment]
Thanks!
