### ISSUE TITLE
'build' does not build nested components

### ISSUE THREAD

**Issue by Kritten** [SAP/ui5-cli#239]
I'm using the SAP WebIDE with the default package.json script command `ui5 build --include-task=generateManifestBundle generateCachebusterInfo`.

My project directory looks like this:
- project
  - webapp
    - manifest.json
    - Component.js
    - components
      - project A
        - webapp
          - manifest.json
          - Component.js
      - project B
        - webapp
          - manifest.json
          - Component.js

## Expected Behavior
The ui5-cli should build all included projects and create a Component-preload.js for `project`, `project A` and `project B` (three Component-preload.js files in total).

## Current Behavior
Only the root project gets build and gets a Componet-preload.js
Every still works but the framework tries to make a request for every nested project`s Component-preload.js which of course fails because there is none.

## Context
- OS/Platform: `SAP WebIDE Fullstack`

## Affected components *(if known)*

- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
Please note: I'm using babel to transpile my code after the build of ui5. Please ignore the corresponding logs ;)
```
09:17:41 (Build) Build started.
09:17:43 (DIBuild) Build of "/project" in progress.
09:17:44 (DIBuild) [INFO] Retrieving source code
09:17:46 (DIBuild) [INFO] Preparing node environment[INFO] package.json not modified, skipping npm installation[INFO] Node environment ready
09:17:50 (DIBuild) [INFO] Set ui5-builder> project@0.0.1 build /tmp/webide.iP6.build/proj> ui5 build --include-task=generateManifestBundle generateCachebusterInfo && babel dist --out-dir dist
09:18:03 (DIBuild) info builder:builder Building project projectnot including dependencies...info builder:builder 🛠  (1/1) Building project projectinfo builder:builder application project🔨 (1/14) Running task escapeNonAsciiCharacters...info builder:builder application project🔨 (2/14) Running task replaceCopyright...info builder:builder application project🔨 (3/14) Running task replaceVersion...info builder:builder application project🔨 (4/14) Running task generateFlexChangesBundle...info builder:processors:bundlers:flexChangesBundler Changes collected. Number of changes: 0info builder:builder application project🔨 (5/14) Running task generateManifestBundle...info builder:builder application project🔨 (6/14) Running task generateComponentPreload...info builder:builder application project🔨 (7/14) Running task createDebugFiles...info builder:builder application project🔨 (8/14) Running task uglify...info builder:builder application project🔨 (9/14) Running task generateVersionInfo...info builder:builder application project🔨 (10/14) Running task webide-extension-task-updateNeoApp...info builder:builder application project🔨 (11/14) Running task webide-extension-task-updateManifestJson...info builder:builder application project🔨 (12/14) Running task webide-extension-task-lint...basevalidator attribute for js in the project.json file is: fioriJsValidator
09:18:15 (DIBuild) basevalidator attribute for xml in the project.json file is: fioriXmlAnalysisinfo builder:builder application project🔨 (13/14) Running task webide-extension-task-resources...info builder:builder application project🔨 (14/14) Running task generateCachebusterInfo...info builder:builder Build succeeded in 11 sinfo builder:builder Executing cleanup tasks...[BABEL] Note: The code generator has deoptimised the styling of /tmp/webide.iP6.build/proj/dist/Component-preload.js as it exceeds the max of 500KB.
09:18:24 (DIBuild) Successfully compiled 111 files with Babel.[INFO] Processing results[INFO] Copying build results to the project folder[INFO] UI5 build finished[INFO] Build finished in 40 seconds
09:18:24 (DIBuild) ********** End of /projectBuild Log **********
09:18:26 (Build) Build completed successfully.
```

**Comment by RandomByte** [comment]
Hey @tommyvinhlam, This should be possible with the `builder.componentPreload` project configuration added with https://github.com/SAP/ui5-builder/pull/6

Apparently there is no documentation for this configuration option. Could you please take over?

**Comment by tommyvinhlam** [comment]
Hi @Kritten, at a first glance, it seems to me that you are having a monorepo, which is kinda not supported. But then I would have expect you having a package.json or a ui5.yaml file in your sub-projects. Would you please confirm, if I am correct?

Anyway, if this is not the case, you can provide additional configuration to the [builder](https://sap.github.io/ui5-tooling/pages/Configuration/#builder-optional) section of your `ui5.yaml`.

See the following example: With the `componentPreload` configuration you can define an array of component namespaces for which you want to generate a component-preload file.

````yaml
builder:
  componentPreload:
    namespaces:
    - namespace/to/project
    - namespace/to/projectA
    - namespace/to/projectB
````

Unfortunately, this configuration option is not documented yet. We will work on this.

I hope this is helping you out.

**Comment by Kritten** [comment]
Hi, thanks for the quick reply.
Yes, I do have a monorepo and every subproject contains the same files as the main project (package.json, ui5.yaml, ...)

_Side note: The main reason for the monorepo was the missing/uncomplete documentation about nesting components in sapui5 espacially regarding the routing between components.
I still tried this approach and as far as I remember the behaviour was different between my 'local' setup using the WebIDE and the deployed app on the testsystem_

I tried using the `componentPreload` setting but it says 
`Error: Resource /resources/namespace/to/ProjectA/Component-preload.js has no content`

Maybe something is wrong with the namespace? 
FYI: I've set the `resourceRoots` setting in my root manifest.json to 
`"namespace.to.ProjectA": "./components/ProjectA/webapp",`

And do I really have to add the root project to the `componentPreload` setting?
I tried to set only the root project (which I thought would be the default behaviour) but then I got 
`Error: No specification version defined for root project debitorManager`

I thank you in advance for your help :)

**Comment by tommyvinhlam** [comment]
Hi @Kritten, thanks for your reply and clarification.
As I said, we do not support monorepos. Amongst other reasons the configuration files (ui5.yaml) of the sub-projects will be ignored.

Regarding the compronentPreload you need to provide the namespaces of your project. The configuration I have showed you was just an example. :)

**Comment by Kritten** [comment]
@tommyvinhlam Of course did I transfer your example to my use case with replacing the namespaces correspondingly ;)

Thank you for your answers. 
As I mentionened in the beginning, it is not such a big deal as long as the project runs.
Maybe monorepos will be supported in the future or I will have time to try nesting components from different components again.
How would this work? I would build the main project and the builder would follow the references to the other project in my workspace and build and include their source into the main project?

**Comment by matz3** [comment]
Regarding monorepos the setup should not be very special. You could have one package per component and one package that depends on them. Then running a `ui5 build --all` should build all the components.

**Comment by matz3** [comment]
Reopening, as the `componentPreload` configuration is actually still not documented.

**Comment by RandomByte** [comment]
I started working on that a while ago: https://github.com/SAP/ui5-tooling/pull/237

There's also a Slack discussion with some feedback that I think still needs to be worked into my change: https://openui5.slack.com/archives/C0A7QFN6B/p1588943990102800

**Comment by matz3** [comment]
Solved via https://github.com/SAP/ui5-tooling/pull/237
