### ISSUE TITLE
How to support Chinese word with i18n file

### ISSUE THREAD

**Issue by zouyi100** [SAP/ui5-cli#278]
## Expected Behavior
"你好" -> "你好"

## Current Behavior
"你好" -> "ä½ å¥½ï¼�é�¹å��ç��"

## Steps to reproduce the issue
1. use i18n_zh.properties file
2. use `sap.ui.getCore().getConfiguration().setLanguage("zh");` to set language to chinese
3. copy "你好" to i18n_zh.properties file as `HELLO_WORD=你好`
4. add a `<Text text="{i18n>HELLO_WORD}">`
5. and you will see the mass code.
6. my i18n_zh.properties file is encoding with UTF-8
7. I has changed it with GKB also ISO-8859-1 but not work well.

## Context

- UI5 Module Version (output of ui5 --version when using the CLI): 1.12.1
- Node.js Version: v10.15.3
- npm Version: 6.13.1
- OS/Platform: Windows 10
- Browser (if relevant): Chrome 79
- Other information:

Here is a similar problem [i18n.properties responds with wrong charset #196](https://github.com/SAP/ui5-server/issues/196)
But i don't think it has been fixed.

So, please help me to solve the problem. Thank you

**Comment by zouyi100** [comment]
And I import my project into webide. The charset is correct.

**Comment by RandomByte** [comment]
Hey @zouyi100,

In step 5, do you use the `ui5 serve` command or do you use `ui5 build` to build the app and test it using a different server?

**Comment by zouyi100** [comment]
Hi, @RandomByte 

In step 5, I used the `ui5 serve -o index.html` command.
And the Chinese words became mass code.

But when I use the 'go live' module in vscode. it works.

Also, I have run `ui5 build` and deploy the dist folder to SCP Cloud Foundry env, and it is also the mass code.

Thank you!

**Comment by RandomByte** [comment]
Thanks. Have you already tried setting the `propertiesFileSourceEncoding` configuration in your ui5.yaml to `UTF-8`?

Documentation: https://sap.github.io/ui5-tooling/pages/Configuration/#encoding-of-properties-files

Example: https://github.com/SAP-samples/openui5-sample-app/blob/master/ui5.yaml

**Comment by zouyi100** [comment]
It works, Thank you!
