### ISSUE TITLE
Provide a "src" option to the build command that changes the cwd for building a project

### ISSUE THREAD

**Issue by cgraff** [SAP/ui5-cli#75]
## Expected Behavior
_ui5 build --src=aGivenProjectFolder_ tells the ui5 builder to set _aGivenProjectFolder_ as cwd. 

Imagine you have to do a transpilation step (babel) before building the project. In this case you don't want to overwrite the current project files, instead you'll place the transpiled project into another folder, e.g. _babel-tmp_. Afterwards you want to build your sapui5 project based on that _babel-tmp_ folder.

## Current Behavior
Currently, the ui5 build command automatically takes the root folder of a project to build it. There is no possibility to tell the builder to build a project from a given source folder.

## Context
- Other information: The use case here is that possibly steps are needed to process (before building the project) that eventually change project files (e.g. babel transpiling)

**Comment by RandomByte** [comment]
While one *could* integrate transpiling using a [Custom Task Extension](https://github.com/SAP/ui5-project/blob/master/docs/BuildExtensibility.md#custom-task-extension) (also see https://github.com/petermuessig/my-es6-ui5-app/), this is still an interesting topic.

I guess you do not want to change the [projects resources configuration](https://github.com/SAP/ui5-project/blob/master/docs/Configuration.md#resources-optional) to point to "`aGivenProjectFolder`" as the server should still use the original source directory? Or is there another reason?

I'm also wondering whether a command line parameter for setting the src directory would be sufficient. Maybe it could be more useful to add an option to specify a different `ui5.yaml` to use for the build.

**Comment by cgraff** [comment]
I honestly guess, the example of @petermuessig supersedes this command (imho).

After getting a better understanding of the ui5 tooling I believe - IF it would be an implementable feature - a _ui5.yaml_ option would be the better choice.

From my point of view this enhancement can be closed.

**Comment by RandomByte** [comment]
Alright, closing this for the time being. Feel free to resurrect if this becomes a requirement again.
